<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\BAR.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
	<Content Include="Data\**\*.*">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		<CopyToPublishDirectory>Always</CopyToPublishDirectory>
	</Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dependencies\UniversalReplacementRandomizer\UniversalReplacementRandomizer\UniversalReplacementRandomizer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Ignite Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Core\CsvTranslation.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Core\FilterArenas.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Core\FilterBosses.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Core\FinalizeTextFile.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Core\HCFilterIds.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Core\InitialDataRead.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Core\Modules.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

</Project>
